### ISSUE TITLE
shelf pinned icon of extension in ChromeOS opens `about:extension` not the extension itself

### ISSUE THREAD

**Issue by chromer030** [inbasic/media-player#20]
Please share a standalone app on chrome web store for ChromeOS users, this app is only one, best native media player of ChromeOS.

**Comment by inbasic** [comment]
1. Right-click on the extension and select "Open in Tab"
2. Close the running instance and press the icon to let the extension load on a browser tab.
3. Go to the "..." menu on Chrome and create a desktop shortcut (More tools -> Create Shortcut). Make sure to check "Open in Window"

**Comment by inbasic** [comment]
You can now uncheck the "Open in Tab" item. So you can have it open in a browser window as normal.
