### ISSUE TITLE
Add support for mkv container

### ISSUE THREAD

**Issue by cyprox972** [inbasic/media-player#21]
Would be great if you could add support for the mkv container

**Comment by chromer030** [comment]
This is the only feature that this great extension lack.
Please add support if it's possible.

**Comment by inbasic** [comment]
MKV is a general video container. So it is pretty hard to have it covered. If you have samples that you can share, I'll take a look.

**Comment by cyprox972** [comment]
Would these sample files be enough?
[https://www.learningcontainer.com/sample-mkv-file/](url)

**Comment by inbasic** [comment]
@cyprox972 If I download these samples and drop them to the player, it plays both of them (using the latest release).

**Comment by inbasic** [comment]
Debug version [media-player.zip](https://github.com/inbasic/media-player/files/7696595/media-player.zip)
