### ISSUE TITLE
keyboard shortcut for speeding up and slowing down video

### ISSUE THREAD

**Issue by pekcheey** [inbasic/media-player#42]
I need a keyboard shortcut to control the playback rate — clicking on the playbackRateMenuButton only increase the rate. to cycle through all the options to get to the next lower playbackRate is awkward. 

Having keyboard shortcuts to control the rate, makes it possible to fast-forward through some boring parts of a video;
I'm watching a lot of video where people talk about stuffs. 

so this is a feature request to have it done properly.
[patch.txt](https://github.com/inbasic/media-player/files/11292225/patch.txt)

But I've taken the liberty of butchering the code to add the functionality. 

I'm ashamed of the patch. but it works. And I'm attaching the patch in the hope it can be useful.

**Comment by pekcheey** [comment]
Thank you!

**Comment by inbasic** [comment]
Cheers!

**Comment by pekcheey** [comment]
hey, not a bug report. but since you might want to update the keyboard shortcut list in 
https://webextension.org/listing/the-media-player.html

**Comment by inbasic** [comment]
Done. Thanks!

https://webextension.org/listing/the-media-player.html?rev
